import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

// Regenerates requirements.lock: every Python package the dev venv and the
// frozen backend install, transitive dependencies included, pinned to exact
// hash-checked versions for BOTH macOS and Windows (--universal), so a fresh
// build environment can never pick up a different version than the one
// tested. A new transitive release broke every transcription once already
// (PyAV 19 vs faster-whisper 1.2.1) in exactly that way.
//
//   npm run lock:python           regenerate after editing a requirements*.txt
//   npm run lock:python -- --check  exit 1 if the lock is out of date (CI)
//
// uv keeps versions already pinned in requirements.lock unless a
// requirements file forces a change, so regenerating never upgrades
// anything by surprise. To deliberately upgrade one package:
//   npm run lock:python -- --upgrade-package <name>

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');
const lockPath = path.join(projectRoot, 'requirements.lock');

const HEADER = [
    '# GENERATED by `npm run lock:python` -- do not edit by hand.',
    '# Every Python package setup:backend, build:backend and CI install,',
    '# pinned with hashes for macOS and Windows. Edit requirements*.txt,',
    '# then regenerate. See scripts/lock-python.mjs.',
    '',
    '',
].join('\n');

// The dev venv's uv (pinned via requirements.lock), else one on PATH -- CI
// installs the lock into the runner's Python instead of a .venv.
const venvUv = process.platform === 'win32'
    ? path.join(projectRoot, '.venv', 'Scripts', 'uv.exe')
    : path.join(projectRoot, '.venv', 'bin', 'uv');
const uv = fs.existsSync(venvUv) ? venvUv : 'uv';

const args = process.argv.slice(2);
const check = args.includes('--check');
const passthrough = args.filter((a) => a !== '--check');

// Compile into a temp file, then compare or replace: --check must never
// touch the real lock, and a failed compile must never truncate it.
const tmpPath = `${lockPath}.tmp`;
if (fs.existsSync(lockPath)) fs.copyFileSync(lockPath, tmpPath);
const result = spawnSync(uv, [
    'pip', 'compile',
    'requirements-dev.txt', 'requirements-build.txt',
    '--universal', '--python-version', '3.12',
    '--generate-hashes', '--no-header',
    '--quiet',
    '-o', tmpPath,
    ...passthrough,
], { cwd: projectRoot, stdio: 'inherit' });
if (result.error || result.status !== 0) {
    fs.rmSync(tmpPath, { force: true });
    console.error(
        result.error
            ? `Couldn't run uv (${result.error.message}). Run "npm run setup:backend" first.`
            : 'uv pip compile failed; requirements.lock was not changed.',
    );
    process.exit(result.status ?? 1);
}

const compiled = fs.readFileSync(tmpPath, 'utf8').replace(/^(# GENERATED[\s\S]*?\n\n)/, '');
fs.rmSync(tmpPath, { force: true });
const next = HEADER + compiled;

// Line endings never count as a difference: a Windows checkout (CI's
// windows-latest uses core.autocrlf=true) has CRLF while uv writes LF, and
// pip reads either. .gitattributes also pins the lock to LF.
const normalize = (text) => text.replace(/\r\n/g, '\n');

if (check) {
    const current = fs.existsSync(lockPath) ? fs.readFileSync(lockPath, 'utf8') : '';
    if (normalize(current) !== normalize(next)) {
        console.error('requirements.lock is out of date with requirements*.txt -- run `npm run lock:python`.');
        process.exit(1);
    }
    console.log('requirements.lock is up to date.');
} else {
    fs.writeFileSync(lockPath, next);
    console.log(`Wrote ${path.relative(projectRoot, lockPath)}.`);
}
